name: Release

on:
  push:
    branches:
      - "**"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Fetch all tags

      - name: Get Changelog Entry
        id: changelog_reader
        uses: dahlia/submark@0.3.1
        with:
          input-file: CHANGELOG.md
          heading-level: 2
          heading-title-text: version ${{ github.ref_name }}
          ignore-case: true
          omit-heading: true

      - name: Get Changelog
        run: |
          echo "${{ steps.changelog_reader.outputs.output-text }}"
      
#      - name: Create Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.github_token }}
#        with:
#          tag_name: ${{ steps.changelog.outputs.tag }}
#          release_name: ${{ steps.changelog.outputs.tag }}
#          body: ${{ steps.changelog.outputs.clean_changelog }}
