on:
  push:
    branches:
      - main

jobs:
  Test_Build:
    name: "Test & Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Fetch all tags

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16.x
          cache-dependency-path: 'yarn.lock'

      - run: 'yarn install --frozen-lockfile'
      - run: 'yarn lint'
      - run: 'yarn test'
      - run: 'yarn build'
      - run: 'yarn build:docs'
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
