on:
  push:
    branches:
      - main

jobs:
    release:
#      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@master
          with:
            fetch-depth: 0 # Fetch all tags
        - name: Build Changelog
          id: github_release
          uses: TriPSs/conventional-changelog-action@v5
            
        - name: Create Release
          uses: softprops/action-gh-release@v2
          with:
            body: ${{steps.github_release.outputs.changelog}}
