on:
  push:
    branches:
      - main

jobs:
    release:
#      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@master
          with:
            fetch-depth: 0 # Fetch all tags
        - name: Build Changelog
          id: github_release
          uses: TriPSs/conventional-changelog-action@v5
            
        - name: Create Release
          uses: actions/create-release@v1
          if: ${{ steps.changelog.outputs.skipped == 'false' }}
          env:
            GITHUB_TOKEN: ${{ secrets.github_token }}
          with:
            tag_name: ${{ steps.changelog.outputs.tag }}
            release_name: ${{ steps.changelog.outputs.tag }}
            body: ${{ steps.changelog.outputs.clean_changelog }}
