on:
  push:
    tags:
      - "v*"

jobs:
    release:
#      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@master
          with:
            fetch-depth: 0 # Fetch all tags
        - name: Build Changelog
          id: github_release
          uses: mikepenz/release-changelog-builder-action@v4
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
        - name: Create Release
          uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
          with:
            body: ${{steps.github_release.outputs.changelog}}
