name: Release
on:
  push:
    tags:
      - "v*"

  workflow_run:
    workflows: ['Unit Test']
    branches: [main]
    types:
      - completed

jobs:
    release:
#      if: startsWith(github.ref, 'refs/tags/')
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
        - run: echo "Branch: ${{ github.ref }}"
        - name: Checkout code
          uses: actions/checkout@master
          with:
            fetch-depth: 0 # Fetch all tags
        - name: Create changelog text
          id: changelog
          uses: loopwerk/tag-changelog@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            exclude_types: other,doc,chore

        - run: echo "${{steps.changelog.outputs.changelog}}"
        
        - name: Create Release
          uses: actions/create-release@v1
          if: ${{ steps.changelog.outputs.skipped == 'false' }}
          env:
            GITHUB_TOKEN: ${{ secrets.github_token }}
          with:
            tag_name: ${{ steps.changelog.outputs.tag }}
            release_name: ${{ steps.changelog.outputs.tag }}
            body: ${{ steps.changelog.outputs.clean_changelog }}
