name: Release

on:
  push:
    branches:
      - "**"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Fetch all tags

      - name: Extract tag from the changelog
        uses: denisa/clq-action@v1
        id: changelog_reader
        with:
          mode: release

      - name: Get Changelog
        run: |
          echo "${{ steps.changelog_reader.outputs.changes }}"
      
#      - name: Create Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.github_token }}
#        with:
#          tag_name: ${{ steps.changelog.outputs.tag }}
#          release_name: ${{ steps.changelog.outputs.tag }}
#          body: ${{ steps.changelog.outputs.clean_changelog }}
